const Courses = [
    {
        id: "1",
        title: "Web Development",
        image: require("../../assets/Course/graphic.jpg"),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, error!",
        courses1: "HTML",
        course2: "CSS",
        course3: "JavaScript",
        price: 5000,
    },
    {
        id: "2",
        title: "Graphic Design",
        image: require("../../assets/Course/graphic.jpg"),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, error!",
        courses1: "HTML",
        course2: "CSS",
        course3: "JavaScript",
        price: 5000,
    },
    {
        id: "3",
        title: "Coding Fundaments",
        image: require("../../assets/Course/graphic.jpg"),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, error!",
        courses1: "C++",
        course2: "Java",
        course3: "Python",
        price: 1000,
    },
    {
        id: "4",
        title: "Ethical Hacking",
        image: require("../../assets/Course/graphic.jpg"),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, error!",
        courses1: "Testing",
        course2: "Exploitation",
        course3: "Linux OS",
        price: 6000,
    },
    {
        id: "5",
        title: "Web Development",
        image: require("../../assets/Course/graphic.jpg"),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, error!",
        courses1: "HTML",
        course2: "CSS",
        course3: "JavaScript",
        price: 5000,
    },
    {
        id: "6",
        title: "Web Development",
        image: require("../../assets/Course/graphic.jpg"),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, error!",
        courses1: "HTML",
        course2: "CSS",
        course3: "JavaScript",
        price: 5000,
    },
];
export default Courses;
// [] array 
// {} object
// [{}] array of object